### ISSUE TITLE
Bootstrap 2 and 3 error on Quickstart

### ISSUE THREAD

**Issue by iafdesign** [locii/zengridframework4-universal#10]
Both bootstrap menu items cause a notice to right of screen and push down content. Joomla basic error reporting on - localhost wamp stack. Setting error to none removes warning but page needs some styling tweaks.

Notice: Undefined property: stdClass::$panel_trigger_text in C:\wamp\www\buildr\templates\buildr\tpls\blocks\panel-trigger.php on line

**Comment by locii** [comment]
All fixed in latest version that I will upload soonish
