### ISSUE TITLE
Build R - background

### ISSUE THREAD

**Issue by iafdesign** [locii/zengridframework4-universal#101]
Not sure this is the correct GitHub for zgfv5 and BuildR - if not please advice where please?

On my version of v.1.0.1 of BuildR the module position "background" is missing from the templatesDetails.xml. So not declared in <positions>.

This may be by design as only specific to some themes, either needs adding or documenting I would suggest.

**Comment by locii** [comment]
Hey Ian - I fixed that earlier today actually.Ill open up zgf and buildr trackers for yoy. Thanks
