### ISSUE TITLE
bug in zengrid v5 zenmenu 

### ISSUE THREAD

**Issue by woodsy751** [locii/zengridframework4-universal#105]
may have found a bug in zengrid v5 zenmenu 
When i group a set of menus on the old version the generated layout was nice see the right screen grab
however no mater what i di i can not duplicate this in Builder for some reason the .zen-menu ul .zen-group ul and the sub menus in it are pushing over 100% width
Can anyone confirm this please
i changed the bg ets as to make it highlite
.zen-menu ul .zen-group ul {
   opacity: 1;
   visibility: visible;
   position: relative;
   left: 0;
   margin: 20px 0 20px -20px !important;
   height: auto;
   box-shadow: none;
    border: 2px solid rgba(225,225,225,0.93);
   background:silver;
    display: inline !important;
    width: 100%!important;
}
![zen_menu](https://cloud.githubusercontent.com/assets/517125/15631767/ac7cdfe0-25bd-11e6-82d6-b4af167a3275.png)

**Comment by woodsy751** [comment]
![menu-1](https://cloud.githubusercontent.com/assets/517125/15631772/ec8f3c2c-25bd-11e6-8702-f5b4be318276.png)

**Comment by locii** [comment]
Can you try with the latest version?
