### ISSUE TITLE
In the old T3 menu one was able to stop a dropdown at a selected level

### ISSUE THREAD

**Issue by woodsy751** [locii/zengridframework4-universal#106]
In V5 this works in CSS
This works in custom css

/_menu off dropdown at various levels_/
.zen-menu-horizontal ul ul ,.zen-menu-horizontal ul ul li {    background-color: transparent; display: none;}/_turns off level 2_/
/_.zen-menu-horizontal ul ul ul,.zen-menu-horizontal ul ul li ul li {    background-color: transparent; display: none;}/_turns off level 3*/

I have tried to set this up in the back end but it does not work

(In) variables.less

// menu overrides
//-------------------------

@drop-menu-level2: null;

(In) themer.xml

```
        <field name="drop-menu-level2" compile="config" type="select" default="normal" label="Show menu at level 2" >
            <option value="background-color: red; display: inline;">Yes</option>
            <option value="background-color: transparent; display: none;">No</option>
        </field>
```

(In) custom.less

/\* Drop down menu limits
-----------------------------------------------------------------------------*/
.zen-menu-horizontal ul ul ,.zen-menu-horizontal ul ul li {  @drop-menu-level2 }

[10:11] 
has anyone an idea on how to get this working? thanks

**Comment by locii** [comment]
So does your custom css work? It's not something I will add to the plugin at this stage.
