### ISSUE TITLE
pagination on a blog page with a dark background needs a look

### ISSUE THREAD

**Issue by woodsy751** [locii/zengridframework4-universal#108]
default the colours are grey  maybe they should be @text-color

.pagination-wrap .counter {
    color: @text-color;
}
i added a pagination active text color
in _pagination.less
around line 41 to 78 
        > a,
        > span {
            .btn-empty();
            display:inline-block;
            padding: 0 10px;
            background:@pagination-bg;
            border:1px solid @pagination-border;
            border-left: 0;
            color:@pagination-text-color;
            min-height:@input-min-height;
            line-height:@input-min-height;
            margin-right: 0;

```
        &:hover {
            border-left: 0;
        }
    }

    &:first-child a{
        border-left: 1px solid @pagination-border
    }



    &.active {
        a {

            background: @btn-primary-bg;
            border: 1px solid @btn-primary-border;
            color:@pagination-active-text-color;

            &:hover {
                background: @btn-primary-bg;
                border: 1px solid @btn-primary-border;
                color:@btn-primary-color-hover;
            }
        }
    }
```

[_pagination.less.zip](https://github.com/locii/zengridframework4-universal/files/288233/_pagination.less.zip)

**Comment by woodsy751** [comment]
![image](https://cloud.githubusercontent.com/assets/517125/15631931/33b9b996-25c4-11e6-86c0-2ac8494d7ef6.png)

**Comment by locii** [comment]
Moved to the buildr repo
