### ISSUE TITLE
Compile Less Button Missing

### ISSUE THREAD

**Issue by edhathaway** [locii/zengridframework4-universal#12]
I'm getting this announcement in the Overview;
"Compile less to css required - Theme panel
Before you saved your theme settings you made some changes that will not display on the front end of your site unless you compile less to css. Click the compile less button in the toolbar to save your changes to the theme's css files."
But, can not locate the 'Compile Less Button' within any of the settings.

**Comment by locii** [comment]
Yes I moved that out of the settings panel and have just combined the buttons. Will remove those warnings oin the next version
