### ISSUE TITLE
Get in touch

### ISSUE THREAD

**Issue by paulus103** [locii/zengridframework4-universal#31]
some slight differences with get in touch button compared to home page to bootstrap 2

![bootstrap2-search-box](https://cloud.githubusercontent.com/assets/3790781/13998787/ed35c824-f130-11e5-9a09-578905943071.png)
![get-in-touch](https://cloud.githubusercontent.com/assets/3790781/13998788/eeffe1da-f130-11e5-8538-f4a63dcac021.png)

**Comment by locii** [comment]
Yeah thats a weird one but can't see why it's happening. Will just run with it for now.
