### ISSUE TITLE
Text underneath and alignment

### ISSUE THREAD

**Issue by paulus103** [locii/zengridframework4-universal#34]
![slideshow-text](https://cloud.githubusercontent.com/assets/3790781/13998992/f0232cb0-f131-11e5-8904-e42884a21439.png)

Can see text for other items and not sure if the text is supposed to line up with the navigation

**Comment by paulus103** [comment]
The text underneath could be my chrome -if you don't see it as being acting up recently

**Comment by locii** [comment]
Yeah I see that as well

**Comment by locii** [comment]
Its a bug with zentools and duplicate slideshow modules on the page
