### ISSUE TITLE
Height difference between single drop down and mega menu

### ISSUE THREAD

**Issue by paulus103** [locii/zengridframework4-universal#41]
![height-difference](https://cloud.githubusercontent.com/assets/3790781/14000343/c064c900-f138-11e5-87af-7334a4b76efc.png)

![height-difference2](https://cloud.githubusercontent.com/assets/3790781/14000344/c2c42290-f138-11e5-8955-f791e67dce8b.png)

I see an issue with mega menu where it flicks on off and on again

**Comment by locii** [comment]
Can you explain this one a bit more.

**Comment by paulus103** [comment]
![heights](https://cloud.githubusercontent.com/assets/3790781/14017498/b4f4c26e-f1bf-11e5-92e6-f0225668e352.png)

There is a different amount of space above a normal dropdown and a mega menu one.

With the mega menu if I hover over the parent item and then move the cursor down to click if disappears and then reappears
