### ISSUE TITLE
Just wondered over icon sizing and space above the lines

### ISSUE THREAD

**Issue by paulus103** [locii/zengridframework4-universal#50]
![icons-size](https://cloud.githubusercontent.com/assets/3790781/14002831/610feb02-f146-11e5-9e60-6916300bd5e4.png)

**Comment by locii** [comment]
I think it looks fine. Can you be more specific?

**Comment by paulus103** [comment]
![610feb02-f146-11e5-9e60-6916300bd5e4](https://cloud.githubusercontent.com/assets/3790781/14017383/ed55bb00-f1be-11e5-9ba1-ebe2261da19b.jpg)

I just thought the space between the line and text was different that content above and maybe the icons were too small in relation to the space left and right of them
