### ISSUE TITLE
Boostrap3 test page has many issues for me

### ISSUE THREAD

**Issue by paulus103** [locii/zengridframework4-universal#58]
http://localhost/buildr25316/templates/buildr/zengrid/libs/zengrid/less/zengrid/fonts/fontawesome-webfont.woff2?v=4.4.0 Failed to load resource: the server responded with a status of 404 (Not Found)

and layout issues

![bs3-buttons](https://cloud.githubusercontent.com/assets/3790781/14047950/f820d2d8-f2a2-11e5-9edb-ce369c8913ee.png)

![navbar-bs3](https://cloud.githubusercontent.com/assets/3790781/14047949/f8203292-f2a2-11e5-9172-49d5aa15de78.png)

**Comment by paulus103** [comment]
forgot the icons pic
![icons](https://cloud.githubusercontent.com/assets/3790781/14047972/1ad3e608-f2a3-11e5-9d3d-fd735fbd2d29.png)

**Comment by locii** [comment]
Fixed the icons but there is an issue with the saved state for the bootstrap options which means the css isnt getting generated. Which is what you see here.
