### ISSUE TITLE
Design panel not showing on qs

### ISSUE THREAD

**Issue by iafdesign** [locii/zengridframework4-universal#8]
Local install of qs from slack/dropbox - all template variation that I tried do not show the design panel with modules, just blue row and white dots, screengrab for you.

![buildr_designpanel](https://cloud.githubusercontent.com/assets/12290466/13875602/cd1541e8-ecf6-11e5-8bf9-aac021dfcc63.png)

**Comment by iafdesign** [comment]
![buildr_designpanel_warning](https://cloud.githubusercontent.com/assets/12290466/13877802/feec98ca-ed04-11e5-8e2e-146b474936f6.png)
Warning screengrab for your information.

Seems there is a missing ajax plugin, which would make sense, so grabbed this file JB_plg_zengridframework_ajax_J3+_1.0.zip and installed/enabled. Then the warnings shown in the template admin for Design tab.

Local install on wamp stack IE and Chrome. Windows 10.

**Comment by locii** [comment]
Do you still get that warning after installing plg from slack?

**Comment by iafdesign** [comment]
Installed plg from Slack and no warning, so that seems to done the trick. Thanks

I will check again, tomorrow, but you can close this issue as I think the plugin has solved it.

**Comment by locii** [comment]
Thanks
