### ISSUE TITLE
Plugin name confusion

### ISSUE THREAD

**Issue by robwent** [locii/zengridframework4-universal#83]
For the new plugin with the ajax functions JB_zengridframework_J2.5_J3.1_1.0

J2.5 needs removing and it could get confused with other framework plugins. Maybe it should start at version 4.0?

I just installed the wrong one as I couldn't tell them apart.

![plg-versions](https://cloud.githubusercontent.com/assets/411678/14080025/2d8b08e0-f4fa-11e5-8859-fa4cbd5e6b50.PNG)

**Comment by locii** [comment]
Yep great point. Thanks

**Comment by locii** [comment]
Actually Ive just chnaged the name to plg_ajax_zengridframework but kept it at v1

**Comment by locii** [comment]
Sound ok?
