### ISSUE TITLE
Page doesn't hold at bottom on Android

### ISSUE THREAD

**Issue by romo1981** [locii/zengridframework4-universal#98]
On my Android phone, Samsung Edge 6, I am unable to scroll to the bottom of the page on all template styles that have the Theme Overview/By The Numbers module. (Responsive may be the only one that doesn't.) The page sits at the bottom briefly, then bounces up to About Us. I didn't see this problem on an iphone or tablet.

**Comment by romo1981** [comment]
I'm not able to duplicate this on any other phone besides the Samsung Edge 6 with the large screen. On other phones, including the Samsung Edge 6 with a standard screen, things work as expected.

**Comment by locii** [comment]
Is that with the default Android browser? There is a default android browser that doesnt handle scroll events at all which is what's causing the issue.

**Comment by romo1981** [comment]
You are correct. Switched to Chome and the issue is non-existent.

**Comment by locii** [comment]
Thanks - I think this is something we will just have to live with for that module. I might look at it in the future again at some time though.
